# Generated by Django 5.2 on 2025-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
                ('video', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(max_length=150)),
                ('ins', models.CharField(max_length=150)),
                ('lin', models.CharField(max_length=150)),
                ('xt', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('newsletter', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=150)),
                ('lang', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('f', models.CharField(max_length=150)),
                ('ins', models.CharField(max_length=150)),
                ('lin', models.CharField(max_length=150)),
                ('xt', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=150)),
                ('text1', models.CharField(max_length=500)),
                ('text2', models.CharField(max_length=500)),
                ('text3', models.CharField(max_length=500)),
                ('text4', models.CharField(max_length=500)),
                ('text5', models.CharField(max_length=500)),
                ('text6', models.CharField(max_length=500)),
                ('text7', models.CharField(max_length=500)),
                ('title1', models.CharField(max_length=150)),
                ('title2', models.CharField(max_length=150)),
                ('title3', models.CharField(max_length=150)),
                ('title4', models.CharField(max_length=150)),
                ('title5', models.CharField(max_length=150)),
                ('title6', models.CharField(max_length=150)),
                ('title7', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('percent', models.IntegerField()),
                ('description_log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField()),
                ('members', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('completed_projects', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField()),
                ('by_user', models.CharField(max_length=150)),
            ],
        ),
    ]
